/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flaregames.task.core;

import java.util.List;

/**
 * Represents cards deck used in Poker game.
 * Contains set of Cards generated by DeckManager
 * @author mustafa
 */
public class Deck {
    
    private List<Card> cards;
    
    
    /**
     * Constructs deck with a set of cards.
     * @param cards 
     */
    public Deck (List<Card> cards){
        this.cards = cards;
    }

    /**
     * 
     * @return deck cards
     */
    public List<Card> getCards() {
        return cards;
    }

    
}
